version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5431:5432"
    volumes:
      - hcm-data:/var/lib/postgresql/data
    networks: [hcm-net]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5

  authapi:
    build:
      context: ./backend/Auth
      dockerfile: Auth.API/Dockerfile
    ports: ["5001:5000"]
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: { db: { condition: service_healthy } }
    networks: [hcm-net]

  peopleapi:
    build:
      context: ./backend/People
      dockerfile: People.API/Dockerfile
    ports: ["5002:5000"]
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on: { db: { condition: service_healthy } }
    networks: [hcm-net]

  vault-init:
    image: curlimages/curl:latest
    depends_on:
      - vault
    entrypoint: ["/bin/sh", "-c", "/vault/init.sh"]
    volumes:
      - ./vault-bootstrap/init.sh:/vault/init.sh
    networks: [hcm-net]

  vault:
    image: hashicorp/vault:1.15.4
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:
      - IPC_LOCK
    networks: [hcm-net]
    volumes:
      - vault-data:/vault/file

networks:
  hcm-net:

volumes:
  hcm-data:
  vault-data: